name: Feature Request
description: Suggest a new feature or enhancement
labels: ["feature", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like?
      placeholder: A clear description of the feature.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      options:
        - "Small — a few hours, single file"
        - "Medium — a day or two, multiple files"
        - "Large — a week+, architectural changes"
